### ISSUE TITLE
RaspberryPi4

### ISSUE THREAD

**Issue by ciB89** [robwolff3/google-assistant-webserver#9]
Does this not work with a Pi4? Unfortunately I get an exec error in my logs :-/

**Comment by ciB89** [comment]
I rebuild the project form arm. I can successfully authenticate but then get the following error in my logs:

```
/usr/local/lib/python3.7/dist-packages/google/assistant/library/assistant.py:90: DeprecationWarning: Google Assistant Library for Python is deprecated


  warnings.warn('Google Assistant Library for Python is deprecated', DeprecationWarning)


Traceback (most recent call last):


  File "/gawebserver.py", line 182, in <module>


    main()


  File "/gawebserver.py", line 133, in main


    with Assistant(credentials, device_model_id) as assistant:


  File "/usr/local/lib/python3.7/dist-packages/google/assistant/library/assistant.py", line 106, in __init__


    credentials, self._set_credentials)


  File "/usr/local/lib/python3.7/dist-packages/google/assistant/library/auth_helpers.py", line 40, in __init__


    self._credentials.refresh(http_request)


  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/credentials.py", line 198, in refresh


    self._scopes,


  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 248, in refresh_grant


    response_data = _token_endpoint_request(request, token_uri, body)


  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request


    _handle_error_response(response_body)


  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/_client.py", line 60, in _handle_error_response


    raise exceptions.RefreshError(error_details, response_body)


google.auth.exceptions.RefreshError: ('invalid_scope: Some requested scopes were invalid. {invalid=[a, c, d, e, g, h, i, k, l, m, -, ., n, /, o, p, r, s, t, u, w, y, :]}', '{\n  "error": "invalid_scope",\n  "error_description": "Some requested scopes were invalid. {invalid\\u003d[a, c, d, e, g, h, i, k, l, m, -, ., n, /, o, p, r, s, t, u, w, y, :]}",\n  "error_uri": "http://code.google.com/apis/accounts/docs/OAuth2.html"\n}')
```

Any ideas how to solve this? Or should I try using a different version of oauth?
